union{
  float f;
  int i;
}u;
#define L 100
struct Dict{
 void * val;
}dict[L];

struct DictM{
 int key;
 void * val;
}dictm[L];
int hash(int key,int length){
  u.i=key;
  u.i=u.i&0x3f7fffff;
  u.i=u.i|0x3f000000;
  return u.f*length;
}

int dictm_store(struct DictM *d,int(*h)(int,int),int key,void * val,int len){
  int k = h(key,len);
  d[k].val=val;
  d[k].key=key;
}
int dict_store(struct Dict *d,int(*h)(int,int),int key,void * val,int len){
   d[h(key,len)].val=val;
}
int main(){
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");

  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  printf("entering main function\n");
  int p=5;
  int i=0;
  printf("%p %d\n",&p,hash((int)&p,L));
  char * st="charStr";
  dict_store(dict,hash,(int)&st,st,L);
  while(i<100){
    printf("%d = %p\n",i,dict[i].val);
    i++;
  }
}
