// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('ldApp').controller("scriptsController", function(configState, command, $rootScope, $scope, $http, Data) {
    var search;
    $scope.bWindows = configState.bWindows;
    $scope.scriptName = '';
    $scope.scriptsList = [
      {
        scriptName: 'name',
        scriptDescription: 'desc'
      }
    ];
    $scope.newScript = function() {
      return $scope.bWindows.push('this is a script placeholder');
    };
    search = function(termList, stringList) {
      return _.filter(stringList, function(el) {
        var f, ff, r, result;
        result = true;
        r = _.map(termList, function(v) {
          return el.match(v);
        });
        f = function(e) {
          if (e) {
            return true;
          }
        };
        ff = _.filter(r, f);
        if (ff.length) {
          return true;
        } else {
          return false;
        }
      });
    };
    $scope.$watch('scriptName', function(n, o) {
      return console.log(search(n.split(" "), _.pluck($scope.scriptsList, 'scriptName')));
    });
    return $scope.scriptsList = [
      {
        scriptName: 'name',
        scriptDescription: 'desc a'
      }, {
        scriptName: 'name one',
        scriptDescription: 'desc bb'
      }, {
        scriptName: 'name two',
        scriptDescription: 'descer wer'
      }, {
        scriptName: 'tree two',
        scriptDescription: 'desc qwe'
      }, {
        scriptName: ' one five ',
        scriptDescription: 'desc 23'
      }, {
        scriptName: 'xis seven',
        scriptDescription: 'desc lk'
      }
    ];
  });

}).call(this);
