// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('ldApp').controller("scriptsController", function(command, $rootScope, $scope, $http, Data) {
    $scope.bWindows = [];
    return $scope.newScript = function() {
      return $scope.bWindows.push({});
    };
  });

}).call(this);
