// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('ldApp').factory('configState', function() {
    var configState;
    return configState = {
      architecture: 'x86 elf',
      file: 'hw',
      TLBEntrySize: 3,
      getMemoryCommand: function(addr) {
        var h, s;
        s = 1 << configState.TLBEntrySize;
        h = s / 2;
        return 'disas /rm ' + addr + ',+' + s;
      }
    };
  });

}).call(this);
